"""fix user model

Revision ID: be44c76ab597
Revises: 6d72b08ddf89
Create Date: 2024-10-12 01:00:31.475143

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "be44c76ab597"
down_revision: Union[str, None] = "6d72b08ddf89"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("is_accountant", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_accountant")
    # ### end Alembic commands ###
