"""fix user relationship with position

Revision ID: 27e16ae23318
Revises: be44c76ab597
Create Date: 2024-10-12 03:02:53.994606

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "27e16ae23318"
down_revision: Union[str, None] = "be44c76ab597"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("position_id", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "users", "positions", ["position_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="foreignkey")
    op.drop_column("users", "position_id")
    # ### end Alembic commands ###
