"""add admin field

Revision ID: f1292aadfaac
Revises: 4cd81a7643b2
Create Date: 2024-10-14 00:32:17.848383

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f1292aadfaac"
down_revision: Union[str, None] = "4cd81a7643b2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "positions",
        sa.Column("name", sa.String(length=70), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "users",
        sa.Column("login", sa.String(), nullable=False),
        sa.Column("picture", sa.String(), nullable=True),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("surname", sa.String(length=70), nullable=False),
        sa.Column("middle_name", sa.String(length=70), nullable=True),
        sa.Column("password", sa.LargeBinary(), nullable=False),
        sa.Column("salary", sa.DECIMAL(precision=12, scale=2), nullable=False),
        sa.Column(
            "create_date", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("login_date", sa.DateTime(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("is_accountant", sa.Boolean(), nullable=False),
        sa.Column("is_admin", sa.Boolean(), nullable=False),
        sa.Column("_phone_number", sa.Unicode(length=20), nullable=False),
        sa.Column("country_code", sa.Unicode(length=8), nullable=False),
        sa.Column("position_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["position_id"],
            ["positions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("login"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    op.drop_table("positions")
    # ### end Alembic commands ###
