"""remove image attach

Revision ID: 4cd81a7643b2
Revises: 108e65062548
Create Date: 2024-10-13 03:54:20.953496

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "4cd81a7643b2"
down_revision: Union[str, None] = "108e65062548"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("userpictures")
    op.add_column("users", sa.Column("picture", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "picture")
    op.create_table(
        "userpictures",
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("width", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("height", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "mimetype", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
        sa.Column("original", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name="userpictures_user_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", "width", "height", name="userpictures_pkey"),
    )
    # ### end Alembic commands ###
