"""add none in position

Revision ID: 71e2c3331aa7
Revises: f1292aadfaac
Create Date: 2024-10-14 03:09:10.520864

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "71e2c3331aa7"
down_revision: Union[str, None] = "f1292aadfaac"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "position_id", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "position_id", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###
