"""add user model and position models

Revision ID: 6d72b08ddf89
Revises: 2099e6a0a8af
Create Date: 2024-10-12 00:24:38.870627

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6d72b08ddf89"
down_revision: Union[str, None] = "2099e6a0a8af"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "positions",
        sa.Column("name", sa.String(length=70), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "users",
        sa.Column("login", sa.String(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("surname", sa.String(length=70), nullable=False),
        sa.Column("middle_name", sa.String(length=70), nullable=True),
        sa.Column("password", sa.LargeBinary(), nullable=False),
        sa.Column("salary", sa.DECIMAL(precision=12, scale=2), nullable=False),
        sa.Column(
            "create_date", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("login_date", sa.DateTime(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("_phone_number", sa.Unicode(length=20), nullable=False),
        sa.Column("country_code", sa.Unicode(length=8), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("login"),
    )
    op.create_table(
        "userpictures",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("width", sa.Integer(), nullable=False),
        sa.Column("height", sa.Integer(), nullable=False),
        sa.Column("mimetype", sa.String(length=255), nullable=False),
        sa.Column("original", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id", "width", "height"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("userpictures")
    op.drop_table("users")
    op.drop_table("positions")
    # ### end Alembic commands ###
